spring.application.name=shop
Jwt.Secret=ahegfuigauighf8aoihfoai6345asg62egs6sg256s5g
expire=3600000
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springdb
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
